### ISSUE TITLE
Congratulations - questions

### ISSUE THREAD

**Issue by BrunoLevy** [Mr-Bossman/rv32_hdl#1]
Congratulations for this awesome work !

I love how you managed to push the implementation of priviledged mode to software, it is amazing, and a great source of inspiration. 
I started to read the RTL and sources, and there is a couple of details I did not understand, would you mind answering a couple of questions ?
My first question: 
- in `system.c`, `xRET` writes `CPUregs->pc`, how do you jump back there in the end ? (I mean, in `cpu.v`, when is it copied to `pc` ?)

Thank you very much in advance !

**Comment by Mr-Bossman** [comment]
So xRET isn't exactly implmeted as you need two instructions for xcall and xret. So in the HDL i  made a cursed instruction to swap the current PC+1 with address 0x4, for an invalid instruction or call/ret. 

https://github.com/Mr-Bossman/KISC-V/blob/93a4381e934fb87ae816e5f974dcd1d50087590f/hdl/cpu.v#L263-L271

So to return from my trap handeller I jump to the address of back in system.S which swaps the old PC in address 0x4 with the PC of _start. We can do a. Similar thing to jump out of the trap handeller to the kernels interrupt handeller by setting the value in address 0x4.

**Comment by BrunoLevy** [comment]
Thank you very much for the explanation (much clearer to me now),
so if I understood well, in `system.S`, the `back: .word 1` corresponds to the cursed instruction (`SYSLOAD`), is that correct ?
Something else I'm struggling to understand:
In `system.c`, there is a struct `cpu_regs` (with `pc`, `reason code`, a `sys` pointer and 32 registers) mapped at address `4`. Now when I read `system.S`, from address 4 I find in that order:
 - `interupt` (initialized with `_start`), mapped to `cpu_regs->pc`
 - `reason_code`, mapped to `cpu_regs->reason_code`
 - space to store value of 32 registers: here I expected to see before the 32 register a word that corresponds to `sys` in the `cpu_regs` structure
 So there is something I did not get, would you shed some light on this ?

**Comment by Mr-Bossman** [comment]
> Thank you very much for the explanation (much clearer to me now), so if I understood well, in `system.S`, the `back: .word 1` corresponds to the cursed instruction (`SYSLOAD`), is that correct ?

Yes that is correct, any instruction that doesn't have an opcode in the base rv32i set will call SYSLOAD.
The exception to this is instruction 0 which is halt.
The Fence and CSR instructions are also explicitly mapped to SYSLOAD.

> Something else I'm struggling to understand: In `system.c`, there is a struct `cpu_regs` (with `pc`, `reason code`, a `sys` pointer and 32 registers) mapped at address `4`. Now when I read `system.S`, from address 4 I find in that order:
> 
> * `interupt` (initialized with `_start`), mapped to `cpu_regs->pc`
> * `reason_code`, mapped to `cpu_regs->reason_code`
> * space to store value of 32 registers: here I expected to see before the 32 register a word that corresponds to `sys` in the `cpu_regs` structure
>   So there is something I did not get, would you shed some light on this ?


That is a bug, thanks for pointing it out.
https://github.com/Mr-Bossman/KISC-V/commit/10fd2b96a23f7eef361a9f7d7397d0c9c44a846c
I still need to check for invalid  instructions in the `entry` function in system.c
